version: "3.9"
services:
  # Service for a ROS 2D SLAM application
  ros1_2d_slam_service:
    # Build the Docker image using the Dockerfile in the same directory
    build: .
    # Set the image name and tag
    image: ros1_2d_slam:latest
    # Define the container name
    container_name: ros1_2d_slam
    # Uncomment the following line to specify a custom user and group ID or name
    #user: "1000:1000"
    # Use the host network for networking, eliminating the need to expose ports or define IP addresses
    network_mode: "host"
    # Enable privileged mode to allow the container to access host devices like USB ports
    privileged: true
    # Define volumes to share directories between the host and the container
    volumes:
      - ../src:/root/ros_ws/src # Map the host source directory to the container's source directory
    # Enable TTY to support GUI display
    tty: true
    # Define environment variables to be passed to the container
    environment:
      - DISPLAY # Required for GUIs to work
    # Use 'tail -f /dev/null' as the entry point to keep the container running
    entrypoint: ["tail", "-f", "/dev/null"]
